controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dashboard:
    path: /dashboard
    controller: App\Controller\Admin\AnlimController::index   